# Generated by Django 5.2.6 on 2025-09-20 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_slug_alter_restaurant_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='qr_code_url',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='slug',
        ),
    ]
